### ISSUE TITLE
Create SlicerOpenAnatomy extension

### ISSUE THREAD

**Issue by cpinter** [PerkLab/SlicerOpenAnatomy#1]
- [x] Use Extension Wizard to create SlicerOpenAnatomy extension
- [x] Extension has one loadable (C++) module called OpenAnatomyExporter
- [ ] Logic can export all the model nodes in the scene as obj files
- [ ] Write out glTF file for the exported obj files using JsonCPP. See an example [here](https://github.com/Slicer/Slicer/blob/79256be785e79d0a732a91c9b3345f3a72250fbe/Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx)

**Comment by lassoan** [comment]
The extension is created and glTF export module is created. We can submit further tasks as new issues.
