### ISSUE TITLE
Export labeled markup points

### ISSUE THREAD

**Issue by rafael-vm** [PerkLab/SlicerOpenAnatomy#17]
Is there a way to export markup points with the .ghlt models? We in the CAVFB (http://200.17.71.18/) would like to use this feature to add topographic descriptions to the bone models we present online.
Thanks in advance, best regards,

@rafael-vm

**Comment by lassoan** [comment]
Yes, sure. You can add a short Python script that adds a sphere model at each point position. All the Slicer method calls that you need for this (get position of each point, add a sphere model at each point) are described in the Slicer Script Repository.

**Comment by rafael-vm** [comment]
@lassoan, thank you, I will look after the proper scripts at the repository to do that. Best regards,
