### ISSUE TITLE
Create gltf exporter

### ISSUE THREAD

**Issue by lassoan** [PerkLab/SlicerOpenAnatomy#3]
It would contain models and volumes. Since 3D textures are not supported in gltf yet, we'll first work on models only. Volumes will be saved as nrrd.

Hierarchy information would be stored externally.

- [ ] Ask on VTK mailing list if anybody is working on gltf exporter already. Ask for comment on our choice of gltf toolkit (do they like it, is there any better suggestion). Send the email draft to Csaba and Andras before posting it to the mailing list.
- [ ] Create a VTK-based exporter (similar to OBJ exporter) - add it to https://github.com/PerkLab/SlicerOpenAnatomy/tree/master/OpenAnatomyExporter/Logic folder
- [ ] Add a test that sets up a simple rendering scene and writes it to gltf  (similar to VTK\IO\Export\Testing\Cxx\TestOBJExporter.cxx)

**Comment by lassoan** [comment]
glTF:
- A data format used primarily for the transfer of 3D scenes. 
- Uses JSON as a base to store certain types of data such as node hierarchy, textures and cameras. 
- glTF uses references to .bin files to store information about 3D structures/textures/colors etc. using URi's
- Some data types are stored in buffers and are retrieved through an accessor method. 
- Coordinate systems and units: 	
  - glTF uses a right-handed coordinates system 
  - Units for all linear distances are meters (angles in radians) 
  - translation is represented as 3D vector, rotations as quaternion, scale as scaling factors along x, y, z axes

Resources:

- https://www.khronos.org/gltf/
- https://github.com/KhronosGroup/glTF/blob/master/README.md
- https://github.com/KhronosGroup/glTF-Blender-Exporter
- https://aframe.io/docs/0.8.0/components/gltf-model.html
- Example gltf files: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/2CylinderEngine/glTF

**Comment by lassoan** [comment]
Do not start from scratch but check out existing converters and libraries. Try to find as small and simple as possible with no external dependencies.

See a list here: https://github.com/KhronosGroup/glTF#c

This one looks quite good: https://github.com/jessey-git/fx-gltf

**Comment by cpinter** [comment]
VTK's new GLTF reader/writer classes are used instead of developing a new one (they appeared suddenly in VTK), see https://github.com/PerkLab/SlicerOpenAnatomy/commit/5592d3e783dc5ffb529f898814001ad003823607
